@startuml
actor User

participant ControllerMainStage
participant Game
participant DatosCompartidos
participant Individuo
participant Recurso
participant Tablero
participant Square
participant Celda

User -> ControllerMainStage: playGame(event)
activate ControllerMainStage
ControllerMainStage -> DatosCompartidos: setGameIniciado(true)
ControllerMainStage -> ControllerMainStage: gameStopped = false
ControllerMainStage -> ControllerMainStage: setDisable(false) {buttonVelocidad}
ControllerMainStage -> ControllerMainStage: select(pauseTab) {tabPaneParametros}
ControllerMainStage -> ControllerMainStage: setDisable(true) {individuoTab}
ControllerMainStage -> ControllerMainStage: setDisable(true) {recursosParametrosTab}
ControllerMainStage -> ControllerMainStage: setDisable(true) {aparicionTab}
ControllerMainStage -> ControllerMainStage: setDisable(true) {anadirTab}
ControllerMainStage -> ControllerMainStage: setDisable(true) {contenidoCeldaTab}
ControllerMainStage -> ControllerMainStage: setDisable(false) {pauseTab}
ControllerMainStage -> ControllerMainStage: setVisible(true) {pauseText}
ControllerMainStage -> ControllerMainStage: setVisible(true) {codigoColor}
ControllerMainStage -> ControllerMainStage: setVisible(false) {playText}
deactivate ControllerMainStage


ControllerMainStage -> DatosCompartidos: isGameIniciado()
activate ControllerMainStage
ControllerMainStage -> DatosCompartidos: getTurnoJuego()
ControllerMainStage -> DatosCompartidos: setTurnoJuego(turno + 1)
ControllerMainStage -> DatosCompartidos: setText(turno + 1)
ControllerMainStage -> Game: turno()
activate Game


Game -> Game: actualizarVidas()
activate Game
Game -> DatosCompartidos: getListaIndividuos()
activate DatosCompartidos
DatosCompartidos -> Individuo: getTurnosVida()
Individuo -> DatosCompartidos: setTurnosVida(vida - 1)
deactivate DatosCompartidos
Game -> DatosCompartidos: getListaRecursos()
activate DatosCompartidos
DatosCompartidos -> Recurso: getTurnosVida()
Recurso -> DatosCompartidos: setTurnosVida(vida - 1)
deactivate DatosCompartidos
deactivate Game


Game -> Game: actualizarProbabilidades()
activate Game
Game -> DatosCompartidos: getListaIndividuos()
activate DatosCompartidos
DatosCompartidos -> Individuo: getProbClon()
Individuo -> DatosCompartidos: setProbClon(probClonacion -10)
DatosCompartidos -> Individuo: getProbRepr()
Individuo -> DatosCompartidos: setProbRepr(probReproduccion -10)
deactivate DatosCompartidos
deactivate Game
@enduml