@startuml
'https://plantuml.com/class-diagram

class Recurso{
- tipoRecurso: Double
- tiempoVida: int
- efecto: int
- square: Square
- celda: int
+ Recurso(tipoRecurso: Double, square: Square)
+ getTipoRecurso(): Double
+ setTipoRecurso(tipoRecurso: Double)
+ getTiempoVida(): int
+ setTiempoVida(tiempoVida: int)
+ getEfecto(): int
+ setEfecto(efecto: int)
+ getSquare(): Square
+ setSquare(square: Square)
+ getCelda(): int
+ setCelda(celda: int)
}
@enduml