@startuml
class com.example.NewInterfaz.DatosCompartidos {
- {static} String altoMatriz
- {static} String anchoMatriz
- {static} String probReproduccion
- {static} String probClonacion
- {static} String vidaInicial
- {static} String aguaVida
- {static} String comidaVida
- {static} String montanaVida
- {static} String tesoroVida
- {static} String bibliotecaVida
- {static} String pozoVida
- {static} String aguaEfecto
- {static} String comidaEfecto
- {static} String montanaEfecto
- {static} String tesoroEfecto
- {static} String bibliotecaEfecto
- {static} String aparicionInicial
- {static} String aguaAparicion
- {static} String comidaAparicion
- {static} String montanaAparicion
- {static} String tesoroAparicion
- {static} String bibliotecaAparicion
- {static} String pozoAparicion
- {static} int anadir
- {static} boolean anadirTab
- {static} boolean contenidoCeldaTab
- {static} int numIndividuos
- {static} int turnoJuego
- {static} double velocidadJuego
- {static} boolean gameIniciado
- {static} ListaEnlazada<Recurso> listaRecursos
- {static} ListaEnlazada<Individuo> listaIndividuos
- {static} ListaEnlazada<Individuo> individuosMuertos
- {static} ListaEnlazada<Square> cuadradosTablero
- {static} Game game
+ {static} ListaEnlazada<Square> getCuadradosTablero()
+ {static} void setCuadradosTablero(ListaEnlazada<Square>)
+ {static} String getAltoMatriz()
+ {static} void setAltoMatriz(String)
+ {static} String getAnchoMatriz()
+ {static} void setAnchoMatriz(String)
+ {static} String getProbReproduccion()
+ {static} void setProbReproduccion(String)
+ {static} String getProbClonacion()
+ {static} void setProbClonacion(String)
+ {static} String getVidaInicial()
+ {static} void setVidaInicial(String)
+ {static} String getAguaVida()
+ {static} void setAguaVida(String)
+ {static} String getComidaVida()
+ {static} void setComidaVida(String)
+ {static} String getMontanaVida()
+ {static} void setMontanaVida(String)
+ {static} String getTesoroVida()
+ {static} void setTesoroVida(String)
+ {static} String getBibliotecaVida()
+ {static} void setBibliotecaVida(String)
+ {static} String getPozoVida()
+ {static} void setPozoVida(String)
+ {static} String getAguaEfecto()
+ {static} void setAguaEfecto(String)
+ {static} String getComidaEfecto()
+ {static} void setComidaEfecto(String)
+ {static} String getMontanaEfecto()
+ {static} void setMontanaEfecto(String)
+ {static} String getTesoroEfecto()
+ {static} void setTesoroEfecto(String)
+ {static} String getBibliotecaEfecto()
+ {static} void setBibliotecaEfecto(String)
+ {static} String getAparicionInicial()
+ {static} void setAparicionInicial(String)
+ {static} String getAguaAparicion()
+ {static} void setAguaAparicion(String)
+ {static} String getComidaAparicion()
+ {static} void setComidaAparicion(String)
+ {static} String getMontanaAparicion()
+ {static} void setMontanaAparicion(String)
+ {static} String getTesoroAparicion()
+ {static} void setTesoroAparicion(String)
+ {static} String getBibliotecaAparicion()
+ {static} void setBibliotecaAparicion(String)
+ {static} String getPozoAparicion()
+ {static} void setPozoAparicion(String)
+ {static} int getAnadir()
+ {static} void setAnadir(int)
+ {static} boolean isAnadirTab()
+ {static} void setAnadirTab(boolean)
+ {static} boolean isContenidoCeldaTab()
+ {static} void setContenidoCeldaTab(boolean)
+ {static} int getNumIndividuos()
+ {static} void setNumIndividuos(int)
+ {static} int getTurnoJuego()
+ {static} void setTurnoJuego(int)
+ {static} double getVelocidadJuego()
+ {static} void setVelocidadJuego(double)
+ {static} boolean isGameIniciado()
+ {static} void setGameIniciado(boolean)
+ {static} ListaEnlazada<Recurso> getListaRecursos()
+ {static} void setListaRecursos(ListaEnlazada<Recurso>)
+ {static} ListaEnlazada<Individuo> getListaIndividuos()
+ {static} void setListaIndividuos(ListaEnlazada<Individuo>)
+ {static} ListaEnlazada<Individuo> getIndividuosMuertos()
+ {static} void setIndividuosMuertos(ListaEnlazada<Individuo>)
+ {static} Game getGame()
+ {static} void setGame(Game)
}


@enduml